name: CD - AI Service

on:
  workflow_run:
    workflows: ["CI - Spring Boot Translate Service"]
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code (needed for Docker build context)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & Push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            anubhav1404/user-ai-service:latest
            anubhav1404/user-ai-service:${{ github.sha }}

  k8s-deploy:
    needs: docker-build
    runs-on: self-hosted  # Your self-hosted runner with kubectl access

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # 1️⃣ Checkout repo (optional if manifests are in same repo)
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Apply AWS credentials secret to cluster (optional if already exists)
      - name: Create AWS Secret
        run: |
          kubectl create secret generic aws-credentials \
            --from-literal=accessK
