name: CD - Spring Boot Translate Service

on:
  workflow_run:
    workflows: ["CI - Spring Boot Translate Service"]   # must match your CI 
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted   # runner must have kubectl + kubeconfig configured

    steps:
      # Checkout repo at the commit that CI built
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      # Configure AWS secret in Kubernetes (replace if exists)
      - name: Configure AWS Secret for K8s
        run: |
          sudo -u ubuntu kubectl delete secret aws-credentials --ignore-not-found
          sudo -u ubuntu kubectl create secret generic aws-credentials \
            --from-literal=accessKey=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=secretKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          sudo -u ubuntu kubectl apply -f kubernetes/

      # Verify rollout of translate service
      - name: Verify rollout
        run: |
          sudo -u ubuntu kubectl rollout status deployment/ai-service


    # - name: DAST (OWASP ZAP baseline)
    #   uses: zaproxy/action-baseline@v0.12.0
    #   with:
    #     target: https://example.com
    #   continue-on-error: true
